version: '3'

services:
  backend-app:
    env_file:
     - server/env
    build: .
    image: backend-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/rasa
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
    networks:
      - node-network


  front-end-app:
    build: client/
    image: front-end-app
    ports:
      - '80:80'
    environment:
      - PORT=80
    depends_on:
      - mongodb
      - backend-app
    volumes:
      - .:/client/
    networks:
      - node-network
    

  mongodb:
    image: mongo:4.2.1-bionic
    restart: always
    command: --quiet
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:    
  dbdata:

networks:
  node-network:
    driver: bridge
